### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by marocchino** [aliencube/CSharp-Coding-Guidelines#2]
- [ ] [Class.Design.Guidelines.md](https://github.com/aliencube/CSharp-Coding-Guidelines/blob/dev/localisation/ko/Class.Design.Guidelines.md)
- [ ] [Documentation.Guidelines.md](https://github.com/aliencube/CSharp-Coding-Guidelines/blob/dev/localisation/ko/Documentation.Guidelines.md) - @nassol 
- [ ] [Framework.Guidelines.md](https://github.com/aliencube/CSharp-Coding-Guidelines/blob/dev/localisation/ko/Framework.Guidelines.md)
- [x] [Layout.Guidelines.md](https://github.com/aliencube/CSharp-Coding-Guidelines/blob/dev/localisation/ko/Layout.Guidelines.md) - @marocchino
- [ ] [Maintainability.Guidelines.md](https://github.com/aliencube/CSharp-Coding-Guidelines/blob/dev/localisation/ko/Maintainability.Guidelines.md)
- [ ] [Member.Design.Guidelines.md](https://github.com/aliencube/CSharp-Coding-Guidelines/blob/dev/localisation/ko/Member.Design.Guidelines.md) - @nassol
- [ ] [Miscellaneous.Design.Guidelines.md](https://github.com/aliencube/CSharp-Coding-Guidelines/blob/dev/localisation/ko/Miscellaneous.Design.Guidelines.md)
- [x] [Naming.Guidelines.md](https://github.com/aliencube/CSharp-Coding-Guidelines/blob/dev/localisation/ko/Naming.Guidelines.md) - @marocchino
- [ ] [Performance.Guidelines.md](https://github.com/aliencube/CSharp-Coding-Guidelines/blob/dev/localisation/ko/Performance.Guidelines.md) - @dyanos
- [ ] [README.md](https://github.com/aliencube/CSharp-Coding-Guidelines/blob/dev/localisation/ko/README.md) - @justinyoo

**Comment by justinyoo** [comment]
My goodness! It's possible!

**Comment by nassol** [comment]
NICE!!

**Comment by nassol** [comment]
이거 하나 맡으려면 어떻게 해요??

**Comment by nassol** [comment]
저는 documentation guidlines 찜~~

**Comment by dyanos** [comment]
전 Performance.Guidelines이거 할께요.

**Comment by nassol** [comment]
@dyanos 화이팅이욤~ !!

**Comment by seoh** [comment]
Framework Guidelines

**Comment by nassol** [comment]
@devthewild  GoGoGo!

**Comment by nassol** [comment]
@dyanos  그런데 dyanos님은 페북에서 어떤 아이디를...?

**Comment by dyanos** [comment]
@nassol Sangjin Sim 입니다용!!

**Comment by nassol** [comment]
@dyanos  아~~~~ 오셨군용~ 이제나 저제나 했네요 ㅎㅎ

**Comment by nassol** [comment]
@marocchino  멤버 디자인 가이드라인 할게요~

**Comment by marocchino** [comment]
관리 안되는거 같으니 그냥 닫아두겠습니다. 'ㅁ')!
