### ISSUE TITLE
Smooth Scroll for Headings in Languages other than English

### ISSUE THREAD

**Issue by justinyoo** [aliencube/CSharp-Coding-Guidelines#3]
IDs for both `<h1>` and `<h2>` elements are not properly inserted when populating contents translated into languages other than English.

eg)

``` html
<h1 id="이-가이드라인에-대하여-about-the-guidelines">이 가이드라인에 대하여 About the Guidelines</h1>
```

should be

``` html
<h1 id="about-the-guidelines">이 가이드라인에 대하여 About the Guidelines</h1>
```

**Comment by marocchino** [comment]
``` md
<a id="about-the-guidelines"></a>
# 이 가이드라인에 대하여 About the Guidelines
```

**Comment by justinyoo** [comment]
Whatever. The point is to programmatically remove "이 가이드라인에 대하여" part or add anchor tags while loading data from AJAX call. Won't manually add additional anchor tags into .md documents.

**Comment by justinyoo** [comment]
Done. I've put extra parenthesis to each headings to make this work.

**Comment by marocchino** [comment]
:+1:
